name: Lighthouse
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17x

      - name: Install and build
        run: npm install
          npm run build

      - name: Audit with lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
        runs: 5
        uploadArtifacts:
          true
          # no urls needed, since it uses local folder to scan .html files
        configPath: '../../.github/workflows/setup/lighthouserc.json'
